# Generated by Django 3.1.4 on 2021-07-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='none', max_length=16)),
                ('otp', models.CharField(default='none', max_length=10)),
            ],
        ),
    ]
